GITHUB_TOKEN = "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"
GITHUB_USER = "Zedagim2002"
GITHUB_REPO = "scholarship-tracker"
GITHUB_FILE = "data.json"
